#!/bin/bash
#
#Requiere:
# - Git
# - Markdown

#Revisamos que las dependencias se cumplan satisfactoriamente
DEPENDENCIES="git markdown"
for dep in $DEPENDENCIES
do
	which $dep > /dev/null;
	if [ $? -ne 0 ]
	then
			echo -e "Dependencia incumplida ${dep}, favor de instalar";
			echo -e "sudo apt-get install ${dep}";
	fi
done;

#optenemos la ruta del repositorio
repo_path=$(git rev-parse --show-toplevel)

#Si no recibe ningún argumento, actualiza todo el directorio
if [ $# -ne 1 ]
then
  echo "Ejecución modo actualización general";
  echo "--------------------------------------------------------------------------------";
  #for file in `git diff --name-only | grep -E '\.md$' | sort `;
  for file in `find $repo_path -iregex ".*\.md$" | sort `;
  do
		$0 $file
	done;
	exit 0;
fi
#Revisamos que el archivo de entrada tenga la extensión adecuada.
(echo ${1} | grep -Evq '\.md$') && (echo "El documento de entrada ${1} debe tener la extension md"; exit 1 );
#generamos el nombre que tendra el archivo de salida
archivo_salida=`echo ${1} | sed 's/\.md$/.html/'`;
echo -e "\t${archivo_salida}";

USER=`eval whoami`
#generamos el titulo
TITLE=`markdown $1 | grep -Eo "<h1>.*</h1>" | head -1 | sed -r  "s/<h1>(.*)<\/h1>/\1/"`
##########################################################################################
#generando el archivo de salida.
##########################################################################################
#Cabecera Html
echo '<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>' > $archivo_salida

#Titulo
echo "<title>$TITLE</title>" >>  $archivo_salida


#Seccion metadatos, css y javascript
echo "<meta http-equiv=\"content-type\" content=\"text/html;charset=utf-8\" />
	<link rel=\"stylesheet\" type=\"text/css\" href=\"http://mundosica.github.com/tutorial_hispano_jQuery/css/style.css\" />
	<script language='Javascript'  type='text/javascript' src='https://ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js'></script>
</head>
<body>
" >> $archivo_salida

#Seccion  Cabecera e inicio del content
echo "<div id='head'>
	<a href='http://mundosica.github.com/tutorial_hispano_jQuery/' id='logoSICA' title='SICÁ - Publicación de códigos abiertos'></a>
	<div id='colaboradores'></div>
</div>
<div id='content'>
" >>  $archivo_salida

markdown $1 >> $archivo_salida

#Fin del content,Agregamos pie de pagina, finalmente cerramos el body y del documento html
echo '</div><!-- end content -->
<div id="pie_pagina">
	<div id="colaboradores">
		<h2>Con especial agredecimiento a:</h2>
		<ul>
				<li><a href="http://mundosica.com">mundosica</a></li>
				<li><a href="http://adsl.mx">ADSL</a></li>
				<li><a href="https://github.com/mundosica/tutorial_hispano_jQuery/contributors">Colaboradores</a></li>
		</ul>
		<br clear="all" />
		<span>Obra está licencia bajo 
			<a rel="license" href="http://creativecommons.org/licenses/by/2.5/mx/">Creative Commons Atribución 2.5 México</a>.
		</span>
	</div>
</div>
</body>
</html>'  >> $archivo_salida
##########################################################################################

#Finalmente mandamos abrir el archivo
gnome-open $archivo_salida &
